# MoveFiles.ps1
# Reads FileList.xlsx (generated by FileList.ps1) in the same folder as this script.
# Sheet layout expected:
#   A1="Directory"  B1="FileName"  C1="move"  D1=<destination folder path>
#   A2.. = source directory   B2.. = file name   C2.. = 1 (move) / blank (skip)
#
# The folder where THIS SCRIPT is located is treated as the "root" reference.
# For every row where column C = 1, moves that file into the destination folder
# specified in D1, RECREATING the same relative sub-folder structure it had
# under the script's own folder. Example:
#   Script folder (root) = C:\work\work
#   Destination           = C:\work\work\move
#   File at                = C:\work\work\浜甲\FooBar\report.xlsx
#   -> moved to            = C:\work\work\move\浜甲\FooBar\report.xlsx
#
# Requires: Microsoft Excel installed on this machine.

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$XlsxPath   = Join-Path $ScriptDir "FileList.xlsx"
$SourceRoot = $ScriptDir   # <- root reference is this script's own folder

if (-not (Test-Path $XlsxPath)) {
    Write-Host "FileList.xlsx not found in $ScriptDir. Please run FileList.ps1 first." -ForegroundColor Red
    exit 1
}

$Excel = New-Object -ComObject Excel.Application
$Excel.Visible = $false
$Excel.DisplayAlerts = $false
$Workbook = $Excel.Workbooks.Open($XlsxPath)
$Sheet = $Workbook.Worksheets.Item(1)

# Read destination folder (D1)
$DestFolder = $Sheet.Cells.Item(1, 4).Text

if ([string]::IsNullOrWhiteSpace($DestFolder)) {
    Write-Host "Destination folder (cell D1) is empty. Aborting." -ForegroundColor Red
    $Workbook.Close($false)
    $Excel.Quit()
    exit 1
}

Write-Host "Root folder (reference): $SourceRoot" -ForegroundColor Cyan

if (-not (Test-Path $DestFolder)) {
    Write-Host "Destination folder does not exist. Creating: $DestFolder" -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $DestFolder -Force | Out-Null
}

# Find the last used row based on column A
$LastRow = $Sheet.Cells.Item($Sheet.Rows.Count, 1).End(-4162).Row  # -4162 = xlUp

$MovedCount   = 0
$SkippedCount = 0

for ($Row = 2; $Row -le $LastRow; $Row++) {
    $Dir      = $Sheet.Cells.Item($Row, 1).Text
    $Name     = $Sheet.Cells.Item($Row, 2).Text
    $MoveFlag = $Sheet.Cells.Item($Row, 3).Text

    if ([string]::IsNullOrWhiteSpace($Dir) -or [string]::IsNullOrWhiteSpace($Name)) {
        continue
    }

    if ($MoveFlag.Trim() -eq "1") {
        $SourcePath = Join-Path $Dir $Name

        # Compute the target sub-folder that preserves the original structure
        if (-not [string]::IsNullOrWhiteSpace($SourceRoot) -and $Dir.StartsWith($SourceRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
            $RelativeDir = $Dir.Substring($SourceRoot.Length).TrimStart('\')
            $TargetDir   = Join-Path $DestFolder $RelativeDir
        }
        else {
            # No usable root -> just drop the file directly into the destination folder
            $TargetDir = $DestFolder
        }

        $TargetPath = Join-Path $TargetDir $Name

        if (Test-Path $SourcePath) {
            try {
                if (-not (Test-Path $TargetDir)) {
                    New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
                }
                Move-Item -Path $SourcePath -Destination $TargetPath -Force
                Write-Host "Moved: $SourcePath -> $TargetPath" -ForegroundColor Green
                $MovedCount++
            }
            catch {
                Write-Host "Failed to move $SourcePath : $($_.Exception.Message)" -ForegroundColor Red
                $SkippedCount++
            }
        }
        else {
            Write-Host "Source file not found, skipped: $SourcePath" -ForegroundColor Yellow
            $SkippedCount++
        }
    }
}

$Workbook.Close($false)
$Excel.Quit()

Write-Host "----------------------------------------" -ForegroundColor Cyan
Write-Host "Done. Moved: $MovedCount file(s), Skipped: $SkippedCount file(s)." -ForegroundColor Cyan
