# MoveFiles.ps1
# Reads FileList.xlsx (generated by FileList.ps1) in the same folder as this script.
# Sheet layout expected:
#   A1="Directory"  B1="FileName"  C1="MoveToDirectory"
#   A2.. = source directory   B2.. = file name   C2.. = destination folder (blank = skip)
#
# For every row where column C is not blank, moves that file (A/B) into the
# destination folder given in column C for that row. The destination folder
# is used as-is (absolute path, or relative to the current working directory).
# If the destination folder doesn't exist, it is created. If a file with the
# same name already exists at the destination, the row is skipped (no overwrite)
# and reported in a "Conflict list" at the end (printed to console AND written
# to ConflictList.txt next to this script, when there's at least one conflict).
#
# Usage:
#   powershell -File work\MoveFiles.ps1        # actually moves files
#   powershell -File work\MoveFiles.ps1 -Pre    # preview only, no file system changes
#
# Requires: Microsoft Excel installed on this machine.

param(
    [switch]$Pre
)

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$XlsxPath  = Join-Path $ScriptDir "FileList.xlsx"
$ModeLabel = if ($Pre) { "[PREVIEW] " } else { "" }

if (-not (Test-Path $XlsxPath)) {
    Write-Host "FileList.xlsx not found in $ScriptDir. Please run FileList.ps1 first." -ForegroundColor Red
    exit 1
}

$Excel = New-Object -ComObject Excel.Application
$Excel.Visible = $false
$Excel.DisplayAlerts = $false
$Workbook = $Excel.Workbooks.Open($XlsxPath)
$Sheet = $Workbook.Worksheets.Item(1)

# Find the last used row based on column A
$LastRow = $Sheet.Cells.Item($Sheet.Rows.Count, 1).End(-4162).Row  # -4162 = xlUp

$MovedCount   = 0
$MissingCount = 0
$ErrorCount   = 0
$Conflicts    = @()

for ($Row = 2; $Row -le $LastRow; $Row++) {
    $Dir     = $Sheet.Cells.Item($Row, 1).Text
    $Name    = $Sheet.Cells.Item($Row, 2).Text
    $DestDir = $Sheet.Cells.Item($Row, 3).Text

    if ([string]::IsNullOrWhiteSpace($Dir) -or [string]::IsNullOrWhiteSpace($Name)) {
        continue
    }

    if ([string]::IsNullOrWhiteSpace($DestDir)) {
        continue   # MoveToDirectory blank -> skip this row
    }

    $SourcePath = Join-Path $Dir $Name
    $TargetPath = Join-Path $DestDir $Name

    if (-not (Test-Path $SourcePath)) {
        Write-Host "${ModeLabel}Source file not found, skipped: $SourcePath" -ForegroundColor Yellow
        $MissingCount++
        continue
    }

    if (Test-Path $TargetPath) {
        $Conflicts += [PSCustomObject]@{ Source = $SourcePath; Target = $TargetPath }
        Write-Host "${ModeLabel}Conflict, target already exists (no overwrite): $TargetPath" -ForegroundColor Yellow
        continue
    }

    if ($Pre) {
        Write-Host "${ModeLabel}Would move: $SourcePath -> $TargetPath" -ForegroundColor Cyan
        $MovedCount++
        continue
    }

    try {
        if (-not (Test-Path $DestDir)) {
            New-Item -ItemType Directory -Path $DestDir -Force | Out-Null
        }
        Move-Item -Path $SourcePath -Destination $TargetPath
        Write-Host "Moved: $SourcePath -> $TargetPath" -ForegroundColor Green
        $MovedCount++
    }
    catch {
        Write-Host "Failed to move $SourcePath : $($_.Exception.Message)" -ForegroundColor Red
        $ErrorCount++
    }
}

$Workbook.Close($false)
$Excel.Quit()

Write-Host "----------------------------------------" -ForegroundColor Cyan
if ($Pre) {
    Write-Host "Preview done. Would move: $MovedCount, missing source: $MissingCount, conflicts: $($Conflicts.Count)" -ForegroundColor Cyan
}
else {
    Write-Host "Done. Moved: $MovedCount, missing source: $MissingCount, failed: $ErrorCount, conflicts: $($Conflicts.Count)" -ForegroundColor Cyan
}

if ($Conflicts.Count -gt 0) {
    Write-Host "`nConflict list (target already exists, skipped):" -ForegroundColor Yellow
    foreach ($c in $Conflicts) {
        Write-Host "  $($c.Source)  ->  $($c.Target)" -ForegroundColor Yellow
    }

    $ConflictLogPath = Join-Path $ScriptDir "ConflictList.txt"
    $ConflictLines = @("Conflict list ($(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')):")
    $ConflictLines += ($Conflicts | ForEach-Object { "$($_.Source)  ->  $($_.Target)" })
    $ConflictLines | Set-Content -Path $ConflictLogPath -Encoding UTF8
    Write-Host "`nConflict list written to: $ConflictLogPath" -ForegroundColor Yellow
}
